preprocess:

  # 1 = Livox
  # 2 = velodyne
  # 3 = Ouster64
  # 4 = HESAIxt32
  # 5 = plain simulation (FlightForge) without additional PCL data
  # 6 = gazebo simulation (x, y, z, intenzity, ring)
  lidar_type: 5

  # this should only be used when the PointCloud has no timestamps which is this case
  scan_rate: 10 # [Hz]
